// Firebase Hosting
export const firebaseHosting = [
  {
    name: 'core' as const,
    score: 1.0,
    scripts: [
      // Firebase core libraries
      /firebase-app\.js/,
      /firebase\/app/,
      /firebase\/9\.\d+\.\d+/,
      // Firebase services
      /firebase-analytics\.js/,
      /firebase-auth\.js/,
      /firebase-firestore\.js/,
      /firebase-storage\.js/,
      /firebase-functions\.js/,
      /firebase-messaging\.js/,
      // Firebase initialization
      /initializeApp|firebase\.initializeApp/,
      /firebaseConfig|FIREBASE_CONFIG/,
      // Firebase SDK usage patterns
      /getAuth\(\)|getFirestore\(\)|getStorage\(\)/,
      /onAuthStateChanged|createUserWithEmailAndPassword|signInWithEmailAndPassword/,
      /collection\(['"].*['"]\)|doc\([^)]+\)\.get\(\)/,
    ],
  },
  {
    name: 'headers' as const,
    score: 1.4,
    headers: {
      // Firebase Hosting specific headers
      server: /Firebase/i,
      'x-firebase-hosting': /.+/,
    },
  },
  {
    name: 'dom-markers' as const,
    score: 0.3,
    documents: [
      // Firebase specific HTML comments
      /<!-- The core Firebase JS SDK is always required and must be listed first -->/,
      // Firebase generated HTML
      /<script\s+defer\s+src="\/\_\_\/firebase\/\d+\.\d+\.\d+\/firebase-app/,
      // Firebase authentication UI
      /firebaseui-auth-container/,
      // Firebase error pages
      /This page was generated by Firebase Hosting/,
    ],
  },
  {
    name: 'filenames' as const,
    score: 0.5,
    filenames: [
      // Firebase Hosting domains
      /\.web\.app\//,
      /\.firebaseapp\.com\//,
      // Firebase SDK paths
      /\/__\/firebase\/\d+\.\d+\.\d+\//,
      // Firebase function paths
      /\/us-central1-.*?\.cloudfunctions\.net\//,
    ],
  },
];
