export const columnMapping = {
  framework: 'framework',
  uiLibrary: 'ui_library',
  httpClient: 'http_client',
  stateManagement: 'state_management',
  bundler: 'bundler',
  minifier: 'minifier',
  router: 'router',
  transpiler: 'transpiler',
  modules: 'modules',
  stylingProcessor: 'styling_processor',
  dates: 'dates',
  platform: 'platform',
  stylingLibraries: 'styling_libraries',
  translations: 'translations',
} as const;
