export const columnMapping = {
  framework: 'framework',
  uiLibrary: 'ui_library',
  httpClient: 'http_client',
  stateManagement: 'state_management',
  bundler: 'bundler',
  minifier: 'minifier',
  router: 'router',
  transpiler: 'transpiler',
  monitoring: 'monitoring',
  modules: 'modules',
  stylingProcessor: 'styling_processor',
  dates: 'dates',
  platform: 'platform',
  stylingLibraries: 'styling_libraries',
  analytics: 'analytics',
  translations: 'translations',
  tableLibrary: 'table_library',
  componentLibrary: 'component_library',
  animation: 'animation',
  formLibrary: 'form_library',
  apiPattern: 'api_pattern',
} as const;
