name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18'

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: server
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            cd /home/server/unbuilt-app

            echo "Pulling latest changes..."
            git pull origin main

            echo "Installing dependencies..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            yarn install

            echo "Building application..."
            yarn build

            echo "Restarting PM2 process..."
            pm2 restart unbuilt

            echo "Deployment completed successfully!"