name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: test  # References the test job from test.yml
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ID: ${{ secrets.SUPABASE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY,SUPABASE_ID
          script: |
            cd /home/server/unbuilt-app && \
            rm -f apps/web/.env && \
            echo "SUPABASE_URL=${SUPABASE_URL}" > apps/web/.env && \
            echo "SUPABASE_KEY=${SUPABASE_KEY}" >> apps/web/.env && \
            echo "SUPABASE_ID=${SUPABASE_ID}" >> apps/web/.env && \
            git pull origin main && \
            yarn install && \
            NODE_ENV=production yarn turbo run build && \
            pm2 delete web || true && \
            NODE_ENV=production pm2 start ecosystem.config.cjs --update-env && \
            pm2 save --force || \
            { echo "Deployment failed at one of the steps"; exit 1; }