name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY
          script: |
            cd /home/server/unbuilt-app && \
            rm -f .env && \
            echo "SUPABASE_URL=${SUPABASE_URL}" > .env && \
            echo "SUPABASE_KEY=${SUPABASE_KEY}" >> .env && \
            git pull origin main && \
            yarn install && \
            NODE_ENV=production SUPABASE_URL=${SUPABASE_URL} SUPABASE_KEY=${SUPABASE_KEY} yarn turbo run build && \
            pm2 delete web || true && \
            NODE_ENV=production SUPABASE_URL=${SUPABASE_URL} SUPABASE_KEY=${SUPABASE_KEY} pm2 start ecosystem.config.cjs --update-env && \
            pm2 save --force || \
            { echo "Deployment failed at one of the steps"; exit 1; }