name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ID: ${{ secrets.SUPABASE_ID }}
      LOGFLARE_SOURCE_TOKEN: ${{ secrets.LOGFLARE_SOURCE_TOKEN }}
      LOGFLARE_API_KEY: ${{ secrets.LOGFLARE_API_KEY }}
      CLARITY_PROJECT_ID: ${{ secrets.CLARITY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn@1.22.19

      - name: Install dependencies
        run: yarn install

      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Build application
        run: yarn turbo run build

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ID: ${{ secrets.SUPABASE_ID }}
      LOGFLARE_SOURCE_TOKEN: ${{ secrets.LOGFLARE_SOURCE_TOKEN }}
      LOGFLARE_API_KEY: ${{ secrets.LOGFLARE_API_KEY }}
      CLARITY_PROJECT_ID: ${{ secrets.CLARITY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY,SUPABASE_ID,LOGFLARE_SOURCE_TOKEN,LOGFLARE_API_KEY,CLARITY_PROJECT_ID
          script: |
            cd /home/server/unbuilt-app && \
            rm -f apps/web/.env && \
            echo "SUPABASE_URL=${SUPABASE_URL}" > apps/web/.env && \
            echo "SUPABASE_KEY=${SUPABASE_KEY}" >> apps/web/.env && \
            echo "SUPABASE_ID=${SUPABASE_ID}" >> apps/web/.env && \
            echo "LOGFLARE_SOURCE_TOKEN=${LOGFLARE_SOURCE_TOKEN}" >> apps/web/.env && \
            echo "LOGFLARE_API_KEY=${LOGFLARE_API_KEY}" >> apps/web/.env && \
            echo "CLARITY_PROJECT_ID=${CLARITY_PROJECT_ID}" >> apps/web/.env && \
            git pull origin main && \
            yarn install && \
            NODE_ENV=production yarn turbo run build && \
            pm2 delete web || true && \
            NODE_ENV=production pm2 start ecosystem.config.cjs --update-env && \
            pm2 save --force || \
            { echo "Deployment failed at one of the steps"; exit 1; }